---
title: "Umówmy się na Polskę, notatki"
author: "Bartosz Chmiela"
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---

# Część 1: Zgoda

## Rozdział 1: Rzeczpospolita naszych marzeń

### Zrobię to lepiej

Problemem jest egocentryzm polityków -- każdy myśli, że jest lepszy i przyniesie dobrobyt swoją władzą.

Problemem Polski jest źle zaprojektowany *ustrój*.

**Ustrój polityczny** -- struktura organizacyjna, kompetencje i określone prawem wzajemne zależności organów państwa (wiki).

### Winny jest system

W demokracji polityka funckjonuje na dwóch poziomach: *normalnym i ustrojowym*. Pierwszy decyduje o funcjonowaniu państwa (np. jakie podatki), drugi o tym w jaki sposób będziemy podejmować decyzje.

Jedynym przykładem zmian ustrojowych były proponowane przez P. Kukiza jednomandatowe okręgi wyborcze, które rzeczywiście zmieniłyby sposób zarządzania krajem.

### Wstydliwy problem wyborców

Problem ustroju Polski dotyczy wyborców, a nie polityków. Ustroje państw, których obywateli dzielą "oczywiste" różnice, muszą aktywnie "zarządzać" tymi różnicami i budować mechanizmy rozładujące napięcia.

### Podsumowując: nasza diagnoza

Akcjologia

:   test

Ideologia

:   test

## Rozdział 2: Centrum silne strategią

## Rozdział 3: Polska równych szans

## Rozdział 4: Harmonia z wyboru

## Rozdział 5: Powrót do demokracji

## Rozdział 6: Umocnienie demokracji

## Komentarz: Wracając do źródeł

## Komentarz: Kręta droga do demokracji

# Część 2: Jesteśmy różni

## Rozdział 7: Wyobraźmy sobie nową umowę

## Rozdział 8: Progresywne wojewódzwtwo marzeń

## Rozdział 9: Konserwatywne województwo marzeń

## Rozdział 10: Lewicowe województwo marzeń

## Rozdział 11: Chadeckie województwo marzeń

## Rozdział 12: Liberalne województwo marzeń

## Komentarz: Europejski sen o polskich marzeniach

## Komentarz: Ku silnej Polsce
